config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy]

  def index
    @items = Item.all.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  def complete
  end


  private
    def set_item
      @item = Item.find(params[:id])
    end
    def item_params
      params.require(:item).permit(:title, :state)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_with(model: item) do |f|
  .form-group
    = f.text_field :title
    = f.hidden_field :state, value: 'false'
  = f.submit class: 'btn'

app/views/items/edit.html.haml
.row
  .col-md-8.offset-md-2
    .main-title
      %h1 Edit Item

      = render 'form', item: @item

app/views/items/index.html.haml
.row
  .col-md-8.offset-md-2
    .main-title
      %h1 All Items
    .items
      %ul.list-group
        - if @items.exists?
          - @items.each do |item|
            %li.list-group-item{class: item.state ? 'completed' : ''}
              = form_for item, url: item_path(item) do |f|
                = f.hidden_field :state, value: 'true'
                = f.button :submit do
                  %i.fas.fa-check
              %span
                = item.title
              .actions
                - unless item.state
                  = link_to edit_item_path(item), class: 'edit' do
                    %i.fas.fa-pen
                = link_to item, class: 'destroy', method: :delete, data: { confirm: 'Are you sure?'} do
                  %i.fas.fa-trash
        - else
          There is no items, to add click on 'New Item'

app/views/items/new.html.haml
.row
  .col-md-8.offset-md-2
    .main-title
      %h1 New Item

      = render 'form', item: @item

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ToDoRails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Varela+Round", :rel => "stylesheet"}
  %body
    #wrapper-header
      %nav.navbar
        .container
          = link_to "ToDo Rails", root_path, {class: 'navbar-brand mr-auto'}
          = link_to "New Item", new_item_path, {class: 'btn my-2 my-lg-0'}

    #wrapper-main
      .container
        = yield

    #wrapper-footer
      .container
        2018 - Realizado por Dumar Ojeda